### ISSUE TITLE
add login customizer plugin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/foliogine-free#15]
We should add login customizer plugin here using TGM activation - https://wordpress.org/plugins/login-customizer/

**Comment by rodica-andronache** [comment]
@ineagu can I close this?

**Comment by ineagu** [comment]
yep


On Thu, Apr 7, 2016 at 3:56 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> can I close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/foliogine-free/issues/15#issuecomment-206882044>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
