### ISSUE TITLE
Unable to clear images (backgrounds, logos, etc)

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/foliogine-free#18]
Hello,

I am unable to remove any kind of custom logos added to the website. Seems that the values are saved or updated when trying different images, but not pressing “Clear image” buttons and applying the changes. After some digging around, it seems that there’s an issue with the image url validator:

```
public function sanitize_imageurl($input,$default = "){

$filetype = wp_check_filetype($input);
if ( $filetype["ext"] ) {
return $input;
}
$filetype = wp_check_filetype($default);
if ( $filetype["ext"] ) {
return $default;
}
return ";
}
```

Don’t know if you’re aware about this issue or not, but I thought I let you know about it since I’m starting to like this theme.

Regards,
Cristian

@rodica-andronache @ineagu

**Comment by rodica-andronache** [comment]
@ineagu can I close this? I think it's not very easy to fix

**Comment by ineagu** [comment]
we can probably discontinue this theme right ? foliogine free/pro ?

Let's start a discussion document with everything you want removed from the
site, we should do this ( remove from theme listing/packages and remove
themes from w.org )

On Thu, Apr 7, 2016 at 3:56 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> can I close this? I think it's not
> very easy to fix
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/foliogine-free/issues/18#issuecomment-206882403>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
