### ISSUE TITLE
No minification of scripts or files unless provide original files. 

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/foliogine-free#7]
No minification of scripts or files unless provide original files. Provide unminified versions of bootstrap.min.js, jquery.min.js, jquery.bxslider.min.js, retina.js, tabs.js and tinynav.min.js

**Comment by HardeepAsrani** [comment]
@ineagu I added every script to /js/src/ folder. However, I wasn't able to find where this theme uses jquery.min.js file.
