### ISSUE TITLE
Redo screenshot with gpl images

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/foliogine-free#8]
Provide license details of images used in screenshot

**Comment by HardeepAsrani** [comment]
I've added the info on readme.txt. Anything else with this one?

**Comment by ineagu** [comment]
@HardeepAsrani the images aren't GPL, for example I am pretty sure the image with the girl in the monitor is not gpl

**Comment by HardeepAsrani** [comment]
Replaced with a GPL image. Check now. @ineagu

**Comment by ineagu** [comment]
thanks
